name: voila-spotify
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - bqplot
  - ipympl
  - seaborn
  - ipywidgets>=7.5
  - pip
  - pip:
    - qgrid>=1.3.0
    - voila>=0.1.21
    - voila-material
    - voila-gridstack
