name: voila-spotify
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - bqplot
  - ipympl
  - seaborn
  - voila==0.1.20
  - voila-material
  - voila-gridstack
  - ipywidgets>=7.5
  - pip
  - pip:
    - qgrid>=1.3.0
