#!/bin/bash

jupyter labextension install @jupyter-widgets/jupyterlab-manager qgrid2
jupyter labextension enable @jupyter-widgets/jupyterlab-manager qgrid2

jupyter nbextension enable --py --sys-prefix qgrid
jupyter nbextension enable --py --sys-prefix widgetsnbextension

jupyter serverextension enable --py --sys-prefix voila


